/**
 * spikeresnet10.h — SpikeResNet10 inference API for STM32F769
 *
 * Network topology (CIFAR-10, 3-channel 32×32 input, T=1 timestep):
 *
 *   block1       Conv(3→64,  3×3, s=1, p=1) + LIF
 *   resBlock2    [Conv(64→64,  3×3)+LIF] × 2  + skip-add (clamp)
 *   downsample3  Conv(64→128, 1×1, s=2, p=0) + LIF         ← skip identity
 *   resBlock4    Conv(64→128, 3×3, s=2)+LIF, Conv(128→128)+LIF + skip-add
 *   downsample5  Conv(128→256,1×1, s=2) + LIF
 *   resBlock6    Conv(128→256,3×3, s=2)+LIF, Conv(256→256)+LIF + skip-add
 *   downsample7  Conv(256→512,1×1, s=2) + LIF
 *   resBlock8    Conv(256→512,3×3, s=2)+LIF, Conv(512→512)+LIF + skip-add
 *   amax9        AdaptiveMaxPool2d(1)
 *   fc9          Linear(512→10)
 *   lifOut       LIF (no reset, output=True — returns membrane voltage)
 *
 * Memory map (float32, worst-case batch=1 single-step inference)
 * ---------------------------------------------------------------
 *   Weights (BN-folded)     : ~18.6 MB  → external SDRAM (0xC0000000)
 *   Membrane states × 13   :  <  1 KB   → internal SRAM (stack or BSS)
 *   Activation buffers × 2  :  ~ 262 KB → DTCM or SRAM1
 *
 * Usage
 * -----
 *   SpikeResNet10Ctx ctx;
 *   spikeresnet10_init(&ctx);           // zero membrane states
 *   float logits[10];
 *   spikeresnet10_forward(&ctx, input_chw, logits);  // single-step inference
 *   int predicted = argmax(logits, 10);
 */

#pragma once
#include <stdint.h>
#include "weights.h"   /* generated by export_weights.py */

/* Input spatial size (CIFAR-10 / SVHN) */
#define NET_H  32
#define NET_W  32
#define NET_C  SPIKERESNET10_NUM_CHANNELS   /* 3 */

/* Largest intermediate feature map: 64 × 32 × 32 = 65 536 floats = 256 KB */
#define ACT_BUF_SIZE  (512 * 32 * 32)   /* conservative upper bound */

/**
 * Per-inference membrane state (one scalar per LIF layer, shape [C,H,W]
 * is spatially shared — each spatial position tracks its own membrane).
 * We keep pointers here; the caller provides the actual storage.
 */
typedef struct {
    /* Membrane buffers — shape matches the corresponding feature map */
    float mem1   [64 * 32 * 32];   /*  64×32×32 =  65 536 f  */
    float mem2_1 [64 * 32 * 32];
    float mem2_2 [64 * 32 * 32];
    float mem_d3 [128 * 16 * 16];  /* 128×16×16 =  32 768 f  */
    float mem4_1 [128 * 16 * 16];
    float mem4_2 [128 * 16 * 16];
    float mem_d5 [256 *  8 *  8];  /* 256×8×8   =  16 384 f  */
    float mem6_1 [256 *  8 *  8];
    float mem6_2 [256 *  8 *  8];
    float mem_d7 [512 *  4 *  4];  /* 512×4×4   =   8 192 f  */
    float mem8_1 [512 *  4 *  4];
    float mem8_2 [512 *  4 *  4];
    float mem_out[SPIKERESNET10_NUM_CLASSES];
} SpikeResNet10Ctx;

/**
 * Zero-initialise all membrane voltages.
 * Call once before the first inference (or to reset between images).
 */
void spikeresnet10_init(SpikeResNet10Ctx *ctx);

/**
 * Run one forward pass (T=1 timestep).
 *
 * @param ctx     Membrane state context (persistent across timesteps if T>1)
 * @param input   Input image [C × H × W] in float32, channel-first
 * @param logits  Output membrane voltages [NUM_CLASSES]
 */
void spikeresnet10_forward(SpikeResNet10Ctx *ctx,
                            const float      *input,
                            float            *logits);

/** Return the argmax of logits[0..n-1]. */
int argmax_f32(const float *v, uint32_t n);
