"""
Export a trained SpikeResNet10 checkpoint to:
  1. A flat binary file of float32 weights (for SDRAM loading on STM32)
  2. A C header declaring extern arrays + a companion .c with the data
     (suitable for linking into STM32CubeIDE projects)

Workflow
--------
  python stm32/export_weights.py \\
      --weights weights/spike/exp1/resnet10_weights_CIFAR10_T_1_E_100_L_mse_count_loss_A_True_S_42.pth \\
      --dataset CIFAR10 \\
      --out     stm32/c_src/weights

The script will:
  • Load and eval the model
  • Fold BatchNorm into Conv (BN parameters are eliminated)
  • Write  weights.bin      — raw float32 blob in layer order
  • Write  weights.h        — C array declarations
  • Write  weights.c        — C array definitions

Memory note
-----------
SpikeResNet10 ≈ 4.9 M float32 params → ~18.6 MB.
These exceed internal Flash (2 MB). Load weights.bin into the 16 MB SDRAM
(mapped at 0xC0000000 on the Discovery board) at startup.
"""

import sys, os, struct, argparse
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

import torch
import numpy as np
from models.spikeresnet import SpikeResNet10Model
from stm32.bn_fold import fold_model, verify_fold

NUM_CLASSES_MAP = {"CIFAR10": 10, "CIFAR100": 100, "SVHN": 10}


# ── Weight ordering ──────────────────────────────────────────────────────────
# Must exactly match the order used by spikeresnet10.c forward pass.
# Each entry: (c_name, module_attr_path)
# After BN-fold every convBlock has [Conv2d, Identity]; weight & bias come
# from the Conv2d.  LIF neurons contribute no learnable parameters (beta and
# threshold are compile-time constants exported separately).

LAYER_ORDER = [
    # (c_symbol_prefix, Python attribute path to the nn.Sequential convBlock)
    ("block1",       "block1.0"),          # Conv2d after fold
    ("resBlock2_1",  "resBlock2_1.0"),
    ("resBlock2_2",  "resBlock2_2.0"),
    ("downsample3",  "downsample3.0"),
    ("resBlock4_1",  "resBlock4_1.0"),
    ("resBlock4_2",  "resBlock4_2.0"),
    ("downsample5",  "downsample5.0"),
    ("resBlock6_1",  "resBlock6_1.0"),
    ("resBlock6_2",  "resBlock6_2.0"),
    ("downsample7",  "downsample7.0"),
    ("resBlock8_1",  "resBlock8_1.0"),
    ("resBlock8_2",  "resBlock8_2.0"),
    ("fc9",          "fc9"),               # nn.Linear
]


def _get_module(model, path: str):
    m = model
    for attr in path.split("."):
        m = getattr(m, attr) if not attr.isdigit() else list(m.children())[int(attr)]
    return m


def _conv_arrays(name: str, module) -> list[dict]:
    """Return weight and bias arrays for a Conv2d or Linear layer."""
    entries = []
    for tensor_name, tensor in [("weight", module.weight.data),
                                 ("bias",   module.bias.data)]:
        arr = tensor.cpu().numpy().astype(np.float32)
        entries.append({
            "c_name":  f"{name}_{tensor_name}",
            "shape":   arr.shape,
            "numel":   arr.size,
            "data":    arr.flatten(),
        })
    return entries


def collect_arrays(model) -> list[dict]:
    arrays = []
    for sym, path in LAYER_ORDER:
        mod = _get_module(model, path)
        arrays.extend(_conv_arrays(sym, mod))
    return arrays


# ── Binary export ────────────────────────────────────────────────────────────

def write_binary(arrays: list[dict], out_path: str) -> int:
    """Write all float32 values contiguously; return total byte count."""
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "wb") as f:
        for a in arrays:
            f.write(a["data"].tobytes())
    total = sum(a["numel"] for a in arrays) * 4
    print(f"  [bin]  {out_path}  ({total/1024/1024:.2f} MB, "
          f"{sum(a['numel'] for a in arrays):,} floats)")
    return total


# ── C header / source export ─────────────────────────────────────────────────

def _c_shape_comment(shape) -> str:
    return "/* " + " x ".join(str(s) for s in shape) + " */"


def write_c_header(arrays: list[dict], out_path: str,
                   beta: float, threshold: float, num_classes: int,
                   num_channels: int) -> None:
    lines = [
        "/* Auto-generated by stm32/export_weights.py — do not edit */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "/* ── Network hyperparameters ──────────────────────────────── */",
        f"#define SPIKERESNET10_NUM_CLASSES   {num_classes}",
        f"#define SPIKERESNET10_NUM_CHANNELS  {num_channels}",
        f"#define SPIKERESNET10_BETA          {beta:.6f}f",
        f"#define SPIKERESNET10_THRESHOLD     {threshold:.6f}f",
        "",
        "/* ── Weight array declarations ────────────────────────────── */",
        "/* All arrays are stored in row-major (C) order.              */",
        "/* Conv2d weight shape: [Cout, Cin, kH, kW]                   */",
        "/* Conv2d bias  shape: [Cout]                                  */",
        "/* Linear weight shape: [Cout, Cin]                            */",
        "/* Linear bias  shape: [Cout]                                  */",
        "",
    ]
    offsets = {}
    byte_offset = 0
    for a in arrays:
        shape_str = _c_shape_comment(a["shape"])
        lines.append(f"extern const float {a['c_name']}[{a['numel']}]; {shape_str}")
        offsets[a["c_name"]] = byte_offset
        byte_offset += a["numel"] * 4

    lines += [
        "",
        "/* ── Byte offsets inside weights.bin (for SDRAM streaming) ── */",
    ]
    for name, off in offsets.items():
        lines.append(f"#define OFFSET_{name.upper():<40} {off}U")

    lines += ["", f"#define SPIKERESNET10_WEIGHTS_TOTAL_BYTES  {byte_offset}U", ""]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  [.h]   {out_path}")


def write_c_source(arrays: list[dict], out_path: str, header_name: str) -> None:
    """
    Write a .c file where every array is placed in a dedicated linker section
    so STM32CubeIDE can map them to external SDRAM via the linker script.
    """
    lines = [
        "/* Auto-generated by stm32/export_weights.py — do not edit */",
        f'#include "{header_name}"',
        "",
        "/* Place weight arrays in .sdram_weights section.            */",
        "/* Map this section to external SDRAM in the linker script:  */",
        "/*   .sdram_weights (NOLOAD) : { *(.sdram_weights) } >SDRAM  */",
        "#define WEIGHT_SECTION __attribute__((section(\".sdram_weights\")))",
        "",
    ]
    for a in arrays:
        shape_str = _c_shape_comment(a["shape"])
        vals = ", ".join(f"{v:.8e}f" for v in a["data"])
        lines += [
            f"WEIGHT_SECTION",
            f"const float {a['c_name']}[{a['numel']}] = {shape_str} {{",
            f"    {vals}",
            "};",
            "",
        ]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  [.c]   {out_path}")


# ── Main ─────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description="Export SpikeResNet10 weights for STM32")
    p.add_argument("--weights",  required=True,
                   help="Path to .pth checkpoint")
    p.add_argument("--dataset",  default="CIFAR10",
                   choices=list(NUM_CLASSES_MAP.keys()))
    p.add_argument("--channels", type=int, default=3,
                   help="Input channels (3 for RGB, 1 for grayscale)")
    p.add_argument("--beta",     type=float, default=0.5)
    p.add_argument("--threshold",type=float, default=1.0)
    p.add_argument("--out",      default="stm32/c_src/weights",
                   help="Output directory")
    p.add_argument("--no-verify", action="store_true",
                   help="Skip numerical BN-fold verification")
    return p.parse_args()


def main():
    args  = parse_args()
    nC    = NUM_CLASSES_MAP[args.dataset]

    print(f"\nLoading {args.weights} …")
    model = SpikeResNet10Model(
        numberOfChannels=args.channels,
        numberOfClasses=nC,
        beta=args.beta,
        threshold=args.threshold,
    )
    ckpt = torch.load(args.weights, map_location="cpu")
    state = ckpt.get("model_state_dict", ckpt)
    model.load_state_dict(state)
    model.eval()

    print("Folding BatchNorm into Conv …")
    folded = fold_model(model)

    if not args.no_verify:
        print("Verifying BN fold …")
        ok = verify_fold(model, folded)
        if not ok:
            print("  WARNING: BN fold verification failed — check rtol tolerance")

    print("Collecting weight arrays …")
    arrays = collect_arrays(folded)

    out = args.out
    write_binary(arrays, os.path.join(out, "weights.bin"))
    write_c_header(arrays, os.path.join(out, "weights.h"),
                   beta=args.beta, threshold=args.threshold,
                   num_classes=nC, num_channels=args.channels)
    write_c_source(arrays, os.path.join(out, "weights.c"),
                   header_name="weights.h")

    print("\nDone.")


if __name__ == "__main__":
    main()
